# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Yield_Estimator
                                 A QGIS plugin
 This plugin estimate yields
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-15
        copyright            : (C) 2026 by Madan
        email                : madanmohanbammidi@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Yield_Estimator class from file Yield_Estimator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .yield_estimator import Yield_Estimator
    return Yield_Estimator(iface)
