# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Yield_Estimator
                                 A QGIS plugin
 This plugin estimate yields
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Madan
        email                : madanmohanbammidi@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

# -*- coding: utf-8 -*-

import os
import traceback
from datetime import datetime

from qgis.PyQt.QtCore import (
    QSettings,
    QTranslator,
    QCoreApplication,
    QThread,
    pyqtSignal
)

from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog

from qgis.core import Qgis, QgsRasterLayer

from .resources import *
from .yield_estimator_dialog import YieldEstimatorDialog, HelpDialog
from .zonal_stats import run_full_zonal_pipeline
from .yield_predictor_ml import run_ml_pipeline


# =========================================================
# LOGGER
# =========================================================

def write_log(log_file, text):

    timestamp = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    line = f"[{timestamp}] {text}"

    print(line)

    with open(log_file, "a", encoding="utf-8") as f:
        f.write(line + "\n")


# =========================================================
# WORKER THREAD
# =========================================================

class WorkerThread(QThread):

    progress = pyqtSignal(int)

    finished = pyqtSignal()

    error = pyqtSignal(str)

    def __init__(
        self,
        vv_files,
        vh_files,
        shp_file,
        field_samples,
        split_pct,
        output_folder,
        algorithm,
        extent
    ):
        super().__init__()

        self.vv_files = vv_files
        self.vh_files = vh_files
        self.shp_file = shp_file
        self.field_samples = field_samples
        self.split_pct = split_pct
        self.output_folder = output_folder
        self.algorithm = algorithm
        self.extent = extent

    def run(self):

        try:

            log_file = os.path.join(
                self.output_folder,
                "plugin_log.log"
            )

            write_log(
                log_file,
                "PLUGIN EXECUTION STARTED"
            )

            # =============================================
            # ZONAL STATS PROGRESS
            # 0-70%
            # =============================================

            def zonal_progress(p):

                self.progress.emit(
                    int(p * 0.7)
                )

            run_full_zonal_pipeline(

                self.vv_files,

                self.vh_files,

                self.shp_file,

                self.output_folder,

                progress_callback=zonal_progress,
                
                log_file=log_file
            )

            write_log(
                log_file,
                "Zonal statistics completed."
            )

            # =============================================
            # ML PIPELINE
            # 70-100%
            # =============================================

            csv_folder = os.path.join(
                self.output_folder,
                "CSV"
            )

            def ml_progress(p):

                self.progress.emit(
                    70 + int(p * 0.3)
                )

            if self.field_samples:

                run_ml_pipeline(

                    gcp_csv=self.field_samples,

                    zonal_csv_folder=csv_folder,

                    output_folder=self.output_folder,

                    algorithm=self.algorithm,

                    progress_callback=ml_progress,

                    log_file=log_file
                )

                write_log(
                    log_file,
                    "ML prediction completed."
                )

            else:

                write_log(
                    log_file,
                    "GCP CSV missing. ML skipped."
                )

            self.progress.emit(100)

            write_log(
                log_file,
                "PLUGIN EXECUTION COMPLETED"
            )

            self.finished.emit()

        except Exception as e:

            traceback.print_exc()

            self.error.emit(str(e))


# =========================================================
# PLUGIN CLASS
# =========================================================

class Yield_Estimator:

    def __init__(self, iface):

        self.iface = iface

        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value('locale/userLocale')[0:2]

        locale_path = os.path.join(

            self.plugin_dir,

            'i18n',

            f'Yield_Estimator_{locale}.qm'
        )

        if os.path.exists(locale_path):

            self.translator = QTranslator()

            self.translator.load(locale_path)

            QCoreApplication.installTranslator(
                self.translator
            )

        self.actions = []

        self.menu = self.tr('&SAR-BIO')

        self.first_start = True

        self.worker = None

    def tr(self, message):

        return QCoreApplication.translate(
            'SAR-BIO',
            message
        )

    def add_action(

        self,

        icon_path,

        text,

        callback,

        enabled_flag=True,

        add_to_menu=True,

        add_to_toolbar=True,

        status_tip=None,

        whats_this=None,

        parent=None
    ):

        action = QAction(

            QIcon(icon_path),

            text,

            parent
        )

        action.triggered.connect(callback)

        action.setEnabled(enabled_flag)

        if status_tip:

            action.setStatusTip(status_tip)

        if whats_this:

            action.setWhatsThis(whats_this)

        if add_to_toolbar:

            self.iface.addToolBarIcon(action)

        if add_to_menu:

            self.iface.addPluginToRasterMenu(
                self.menu,
                action
            )

        self.actions.append(action)

        return action

    def initGui(self):

        icon_path = ':/plugins/yield_estimator/icon.png'

        self.add_action(

            icon_path,

            text=self.tr('SAR-BIO'),

            callback=self.run,

            parent=self.iface.mainWindow()
        )

    def unload(self):

        for action in self.actions:

            self.iface.removePluginRasterMenu(

                self.tr('&SAR-BIO'),

                action
            )

            self.iface.removeToolBarIcon(action)

    def run(self):

        if self.first_start:

            self.dlg = YieldEstimatorDialog()

            self.dlg.pbVV.clicked.connect(self.select_vv)

            self.dlg.pbVH.clicked.connect(self.select_vh)

            self.dlg.pbClassified.clicked.connect(self.select_shp)

            self.dlg.pbOutput.clicked.connect(self.select_output)

            self.dlg.pbGCP.clicked.connect(self.select_samples)

            self.dlg.pbHelp.clicked.connect(self.open_help)

            self.dlg.pbPredict.clicked.connect(
                self.run_estimation
            )

            self.dlg.pbReset.clicked.connect(
                self.reset_all
            )

            self.dlg.pbCancel.clicked.connect(
                self.cancel_process
            )

            self.first_start = False

        self.dlg.exec_()

    # =====================================================
    # FILE PICKERS
    # =====================================================

    def select_vv(self):

        files, _ = QFileDialog.getOpenFileNames(

            self.dlg,

            "Select VV Rasters",

            "",

            "TIFF (*.tif *.tiff)"
        )

        if files:

            self.dlg.leVV.setText(";".join(files))

            self.update_extent(files)

    def select_vh(self):

        files, _ = QFileDialog.getOpenFileNames(

            self.dlg,

            "Select VH Rasters",

            "",

            "TIFF (*.tif *.tiff)"
        )

        if files:

            self.dlg.leVH.setText(";".join(files))

    def select_shp(self):

        file, _ = QFileDialog.getOpenFileName(

            self.dlg,

            "Select Shape File",

            "",

            "Shapefile (*.shp)"
        )

        if file:

            self.dlg.leClassified.setText(file)

    def select_samples(self):

        file, _ = QFileDialog.getOpenFileName(

            self.dlg,

            "Select GCP CSV",

            "",

            "CSV (*.csv)"
        )

        if file:

            self.dlg.leGCP.setText(file)

    def select_output(self):

        folder = QFileDialog.getExistingDirectory(

            self.dlg,

            "Select Output Folder"
        )

        if folder:

            self.dlg.leOutput.setText(folder)

    # =====================================================
    # EXTENT
    # =====================================================

    def update_extent(self, files):

        if not files:
            return

        lyr = QgsRasterLayer(files[0])

        if not lyr.isValid():
            return

        ext = lyr.extent()

        self.dlg.leMinX.setText(
            str(ext.xMinimum())
        )

        self.dlg.leMinY.setText(
            str(ext.yMinimum())
        )

        self.dlg.leMaxX.setText(
            str(ext.xMaximum())
        )

        self.dlg.leMaxY.setText(
            str(ext.yMaximum())
        )

    # =====================================================
    # HELP
    # =====================================================

    def open_help(self):

        if not hasattr(self, "help_dlg"):

            self.help_dlg = HelpDialog(self.dlg)

        self.help_dlg.show()

        self.help_dlg.raise_()

        self.help_dlg.activateWindow()

    # =====================================================
    # RESET
    # =====================================================

    def reset_all(self):

        self.dlg.reset_fields()

    # =====================================================
    # CANCEL
    # =====================================================

    def cancel_process(self):

        if self.worker:

            self.worker.requestInterruption()

            self.worker.quit()

            self.worker.wait()

            self.worker = None

        self.dlg.set_running(False)

        self.iface.messageBar().pushMessage(

            "Cancelled",

            "Process cancelled by user",

            level=Qgis.Warning
        )

    # =====================================================
    # MAIN PROCESS
    # =====================================================

    def run_estimation(self):

        try:

            vv_files = [

                f.strip()

                for f in self.dlg.leVV.text().split(";")

                if f.strip()
            ]

            vh_files = [

                f.strip()

                for f in self.dlg.leVH.text().split(";")

                if f.strip()
            ]

            shp = self.dlg.leClassified.text().strip()

            samples = self.dlg.leGCP.text().strip()

            output = self.dlg.leOutput.text().strip()

            split = self.dlg.sbSplit.value()

            algo = self.dlg.cbAlgorithm.currentText()

            extent = {

                "minx": self.dlg.leMinX.text(),

                "miny": self.dlg.leMinY.text(),

                "maxx": self.dlg.leMaxX.text(),

                "maxy": self.dlg.leMaxY.text()
            }

            if not vv_files or not vh_files or not shp or not output:

                self.iface.messageBar().pushMessage(

                    "Error",

                    "Missing required inputs",

                    level=Qgis.Critical
                )

                return

            self.dlg.set_running(True)

            self.dlg.progressBar.setValue(0)

            self.worker = WorkerThread(

                vv_files,

                vh_files,

                shp,

                samples,

                split,

                output,

                algo,

                extent
            )

            self.worker.progress.connect(

                self.dlg.progressBar.setValue
            )

            self.worker.finished.connect(
                self.on_finished
            )

            self.worker.error.connect(
                self.on_error
            )

            self.worker.start()

            self.iface.messageBar().pushMessage(

                "Info",

                "Processing started...",

                level=Qgis.Info
            )

        except Exception as e:

            traceback.print_exc()

            self.iface.messageBar().pushMessage(

                "Error",

                str(e),

                level=Qgis.Critical
            )

    # =====================================================
    # CALLBACKS
    # =====================================================

    def on_finished(self):

        self.dlg.set_running(False)

        self.dlg.progressBar.setValue(100)

        if self.worker:

            self.worker.quit()

            self.worker.wait()

            self.worker = None

        self.iface.messageBar().pushMessage(

            "Success",

            "Processing completed",

            level=Qgis.Success
        )

    def on_error(self, msg):

        self.dlg.set_running(False)

        if self.worker:

            self.worker.quit()

            self.worker.wait()

            self.worker = None

        self.iface.messageBar().pushMessage(

            "Error",

            msg,

            level=Qgis.Critical
        )