# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Yield_EstimatorDialog
                                 A QGIS plugin
 This plugin estimate yields
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Madan
        email                : madanmohanbammidi@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic, QtWidgets
from qgis.PyQt.QtCore import Qt

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'yield_estimator_dialog_base.ui'
    )
)

class YieldEstimatorDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None):

        super().__init__(parent)

        self.setupUi(self)

        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(100)
        self.progressBar.setValue(0)

        self.progressBar.setFormat("%p% Completed")
        self.progressBar.setAlignment(Qt.AlignCenter)

        self._is_running = False

    def set_running(self, state: bool):

        self._is_running = state

        self.pbPredict.setEnabled(not state)

        self.pbVV.setEnabled(not state)
        self.pbVH.setEnabled(not state)
        self.pbClassified.setEnabled(not state)
        self.pbOutput.setEnabled(not state)
        self.pbGCP.setEnabled(not state)

        self.pbReset.setEnabled(not state)

        self.pbCancel.setEnabled(state)

        if state:
            self.progressBar.setValue(0)

    def reset_fields(self):

        self.leMinX.clear()
        self.leMinY.clear()
        self.leMaxX.clear()
        self.leMaxY.clear()

        self.leVV.clear()
        self.leVH.clear()

        self.leClassified.clear()

        self.leGCP.clear()

        self.leOutput.clear()

        self.sbSplit.setValue(30)

        self.cbAlgorithm.setCurrentIndex(0)

        self.progressBar.setValue(0)


HELP_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'help.ui'
    )
)

class HelpDialog(QtWidgets.QDialog, HELP_CLASS):

    def __init__(self, parent=None):

        super().__init__(parent)

        self.setupUi(self)
        
        self.setWindowFlags(
            Qt.Window |
            Qt.WindowStaysOnTopHint |
            Qt.Tool
        )